import urllib.request, json
import re
import os

url = "https://www.googleapis.com/drive/v3/files?q='1pbzpdOKtL3b9O82Te5ioAg7V1m2I9a9T'+in+parents&key=AIzaSyDsU6PU46SENJQAw35YQOI8OAMfHAoEUBs&fields=files(id,name,description,webViewLink,thumbnailLink,mimeType,size,createdTime)&pageSize=1000"
r = urllib.request.urlopen(url)
data = json.loads(r.read().decode('utf-8'))

documents = []
for file in data.get('files', []):
    filename = file.get('name', '')
    if not filename.endswith('.pdf'): continue
    
    # same regex logic
    date_match = re.search(r'(\d{4}-\d{2}-\d{2})', filename)
    date_str = date_match.group(1) if date_match else '2000-01-01'
    year = int(date_str.split('-')[0])
    
    clean_parts = re.sub(r'\.(pdf|jpe?g|png)$', '', filename, flags=re.IGNORECASE)
    clean_parts = [p for p in clean_parts.split('_') if len(p) > 2 and not re.match(r'^\d{4}-\d{2}-\d{2}$', p) and not re.match(r'^PER$', p, re.IGNORECASE)]
    
    header = "01_REVISTAS"
    detail = file.get('description', filename.replace('.pdf', ''))
    
    desc = file.get('description', '')
    
    thumb = file.get('thumbnailLink', '')
    if thumb:
        thumb = thumb.replace('=s220', '=s1024')
        
    doc = {
        "id": "DRIVE_" + file['id'],
        "driveId": file['id'],
        "title": filename.replace(".pdf", "").replace("_", " "),
        "description": desc,
        "date": date_str,
        "year": year,
        "eraId": "S21", # fallback
        "header": header,
        "location": "Archivo Hemeroteca",
        "regions": ["GENERAL"],
        "type": "newspaper",
        "media": {
            "thumbnail": thumb,
            "pdf": file['id'],
            "driveFileId": file['id'],
            "viewUrl": f"https://drive.google.com/file/d/{file['id']}/view"
        },
        "tags": ["Drive", "01_REVISTAS", "Sincronizado"],
        "_source": "drive",
        "localPath": "01_REVISTAS"
    }
    # era logic - adaptado
    if 711 <= year <= 1031: doc['eraId'] = "E1_CALIFATO"
    elif 1031 <= year <= 1086: doc['eraId'] = "E2_TAIFAS"
    elif 1900 <= year <= 1999: doc['eraId'] = "S20"
    else: doc['eraId'] = "S21"
    
    documents.append(doc)

app_data = "c:/Users/leoga/Desktop/Noor/Antigravity Macro- Proyecto Drive/js/data/mock-data.js"
with open(app_data, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by AntiGravity Drive Sync\n')
    f.write('window.NoorMockData = ' + json.dumps(documents, indent=2, ensure_ascii=False) + ';\n')

dest_dir = "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/"
if os.path.exists(dest_dir):
    try:
        os.makedirs(os.path.join(dest_dir, 'SigloXX'), exist_ok=True)
        with open(os.path.join(dest_dir, 'SigloXX', 'metadatos.json'), 'w', encoding='utf-8') as f:
            json.dump(documents, f, indent=2, ensure_ascii=False)
        print("Metadatos escritos en Drive exitosamente.")
    except Exception as e:
        print("Error escribiendo en G:", e)

print(f"Sync completo: {len(documents)} documentos detectados y parseados.")
