    {
      "id": "local-ctx-06_1981_DIG_La_Cuisine_Algerienne_Rescat",
      "driveId": "1d0XUYRWUDV2IREFNsOgr5dFutVsR3Flu",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_1981_DIG_La_Cuisine_Algerienne_Rescate",
      "year": 1981,
      "type": "book",
      "eraId": "CONTEMPORARY",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_1981_DIG_La_Cuisine_Algerienne_Rescate.pdf",
      "media": { "driveFileId": "1d0XUYRWUDV2IREFNsOgr5dFutVsR3Flu", "pdf": "1d0XUYRWUDV2IREFNsOgr5dFutVsR3Flu", "thumbnail": "https://drive.google.com/thumbnail?id=1d0XUYRWUDV2IREFNsOgr5dFutVsR3Flu&sz=w1000" }
    },
    {
      "id": "local-ctx-06_1998_DIG_Etnobot_nica_Rescate",
      "driveId": "1CiYfmtje7HKgOmBNR2oHEt3kIIIb2fbZ",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_1998_DIG_Etnobotánica_Rescate",
      "year": 1998,
      "type": "book",
      "eraId": "CONTEMPORARY",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_1998_DIG_Etnobotánica_Rescate.pdf",
      "media": { "driveFileId": "1CiYfmtje7HKgOmBNR2oHEt3kIIIb2fbZ", "pdf": "1CiYfmtje7HKgOmBNR2oHEt3kIIIb2fbZ", "thumbnail": "https://drive.google.com/thumbnail?id=1CiYfmtje7HKgOmBNR2oHEt3kIIIb2fbZ&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2000_DIG_Contextualizaci_n_Bot_nica_e",
      "driveId": "1N8AI8_tLwxJwomutM0Y-Pk1XMM1JM6n1",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2000_DIG_Contextualización_Botánica económica y Etnobotánica",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2000_DIG_Contextualización_Botánica económica y Etnobotánica.pdf",
      "media": { "driveFileId": "1N8AI8_tLwxJwomutM0Y-Pk1XMM1JM6n1", "pdf": "1N8AI8_tLwxJwomutM0Y-Pk1XMM1JM6n1", "thumbnail": "https://drive.google.com/thumbnail?id=1N8AI8_tLwxJwomutM0Y-Pk1XMM1JM6n1&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2000_DIG_Sabores__rabe",
      "driveId": "1q9X_pcZXMOoavZrlL_PZ_kT4cFdvxZ3L",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2000_DIG_Sabores_Árabe_",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2000_DIG_Sabores_Árabe_.pdf",
      "media": { "driveFileId": "1q9X_pcZXMOoavZrlL_PZ_kT4cFdvxZ3L", "pdf": "1q9X_pcZXMOoavZrlL_PZ_kT4cFdvxZ3L", "thumbnail": "https://drive.google.com/thumbnail?id=1q9X_pcZXMOoavZrlL_PZ_kT4cFdvxZ3L&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2000_Meigasil_Cocina_Arabe_Paso_a_Pas",
      "driveId": "19KVOliCv6cgdcRHTCnj-4eyhX2j8pq_n",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2000_Meigasil_Cocina-Arabe-Paso-a-Paso_S-XX",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2000_Meigasil_Cocina-Arabe-Paso-a-Paso_S-XX.pdf",
      "media": { "driveFileId": "19KVOliCv6cgdcRHTCnj-4eyhX2j8pq_n", "pdf": "19KVOliCv6cgdcRHTCnj-4eyhX2j8pq_n", "thumbnail": "https://drive.google.com/thumbnail?id=19KVOliCv6cgdcRHTCnj-4eyhX2j8pq_n&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2003_DIG_Cocina_Marroqu",
      "driveId": "14uMpKa-zBD7eWQTWOvO2XgFVoACK96PB",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2003_DIG_Cocina_Marroquí",
      "year": 2003,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2003_DIG_Cocina_Marroquí.pdf",
      "media": { "driveFileId": "14uMpKa-zBD7eWQTWOvO2XgFVoACK96PB", "pdf": "14uMpKa-zBD7eWQTWOvO2XgFVoACK96PB", "thumbnail": "https://drive.google.com/thumbnail?id=14uMpKa-zBD7eWQTWOvO2XgFVoACK96PB&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2004_DIG_Cocina_Turca",
      "driveId": "1HeH1b5ha7Xzn2-E33rPbCIitn01UoIXK",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2004_DIG_Cocina_Turca",
      "year": 2004,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2004_DIG_Cocina_Turca.pdf",
      "media": { "driveFileId": "1HeH1b5ha7Xzn2-E33rPbCIitn01UoIXK", "pdf": "1HeH1b5ha7Xzn2-E33rPbCIitn01UoIXK", "thumbnail": "https://drive.google.com/thumbnail?id=1HeH1b5ha7Xzn2-E33rPbCIitn01UoIXK&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2004_DIG_Recetario_Cocina_Turca",
      "driveId": "1l712o07C94NTcpLy-W274swQoGfVOAZ3",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2004_DIG_Recetario_Cocina_Turca",
      "year": 2004,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2004_DIG_Recetario_Cocina_Turca.pdf",
      "media": { "driveFileId": "1l712o07C94NTcpLy-W274swQoGfVOAZ3", "pdf": "1l712o07C94NTcpLy-W274swQoGfVOAZ3", "thumbnail": "https://drive.google.com/thumbnail?id=1l712o07C94NTcpLy-W274swQoGfVOAZ3&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2005_06_09_DIG_Nuevas_Tecnolog_as_Cen",
      "driveId": "1r45-hCXHCX_rF2nU2SQQXCXU_lmFfGwK",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2005_06_09_DIG_Nuevas_Tecnologías_Centro_Tec_Innovación_Paco_Morales",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2005_06_09_DIG_Nuevas_Tecnologías_Centro_Tec_Innovación_Paco_Morales.Pdf",
      "media": { "driveFileId": "1r45-hCXHCX_rF2nU2SQQXCXU_lmFfGwK", "pdf": "1r45-hCXHCX_rF2nU2SQQXCXU_lmFfGwK", "thumbnail": "https://drive.google.com/thumbnail?id=1r45-hCXHCX_rF2nU2SQQXCXU_lmFfGwK&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2005_10_DIG_Mapa_Procesos",
      "driveId": "1zo3ccWuHV-cbHUUDlP65K7t21bfX1mUQ",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2005_10_DIG_Mapa_Procesos",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2005_10_DIG_Mapa_Procesos.pdf",
      "media": { "driveFileId": "1zo3ccWuHV-cbHUUDlP65K7t21bfX1mUQ", "pdf": "1zo3ccWuHV-cbHUUDlP65K7t21bfX1mUQ", "thumbnail": "https://drive.google.com/thumbnail?id=1zo3ccWuHV-cbHUUDlP65K7t21bfX1mUQ&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2005_Behnke_Cocina_Oriente_Medio_Guia",
      "driveId": "1UJx9TSqPLlt-ddxU_bwdvSJ-ouwPQhaY",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2005_Behnke_Cocina-Oriente-Medio-Guia_S-XXI",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2005_Behnke_Cocina-Oriente-Medio-Guia_S-XXI.pdf",
      "media": { "driveFileId": "1UJx9TSqPLlt-ddxU_bwdvSJ-ouwPQhaY", "pdf": "1UJx9TSqPLlt-ddxU_bwdvSJ-ouwPQhaY", "thumbnail": "https://drive.google.com/thumbnail?id=1UJx9TSqPLlt-ddxU_bwdvSJ-ouwPQhaY&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2005_DIG_Recetario_Cocina__rabe",
      "driveId": "1tfrIplfoSNIsImBeb3aeTrYc-5q6t0T_",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2005_DIG_Recetario_Cocina_Árabe",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2005_DIG_Recetario_Cocina_Árabe.pdf",
      "media": { "driveFileId": "1tfrIplfoSNIsImBeb3aeTrYc-5q6t0T_", "pdf": "1tfrIplfoSNIsImBeb3aeTrYc-5q6t0T_", "thumbnail": "https://drive.google.com/thumbnail?id=1tfrIplfoSNIsImBeb3aeTrYc-5q6t0T_&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2005_Estudio_Tejidos_Al_Andalus_Parte",
      "driveId": "1jehOid_alnkWJRDIukBHemi9TqwPVQtG",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2005_Estudio_Tejidos_Al-Andalus_Partearroyo.pdf",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2005_Estudio_Tejidos_Al-Andalus_Partearroyo.pdf.pdf",
      "media": { "driveFileId": "1jehOid_alnkWJRDIukBHemi9TqwPVQtG", "pdf": "1jehOid_alnkWJRDIukBHemi9TqwPVQtG", "thumbnail": "https://drive.google.com/thumbnail?id=1jehOid_alnkWJRDIukBHemi9TqwPVQtG&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2006_08_29_DIG_Contextualizaci_n_Alga",
      "driveId": "1z1yEea1IBwr93j0BIN_o1fSz_T8mJhD7",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2006_08_29_DIG_Contextualización_Algas",
      "year": 2006,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2006_08_29_DIG_Contextualización_Algas.pdf",
      "media": { "driveFileId": "1z1yEea1IBwr93j0BIN_o1fSz_T8mJhD7", "pdf": "1z1yEea1IBwr93j0BIN_o1fSz_T8mJhD7", "thumbnail": "https://drive.google.com/thumbnail?id=1z1yEea1IBwr93j0BIN_o1fSz_T8mJhD7&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2006_09_22_DIG_Andoni_Procesos",
      "driveId": "1fyRs1756TUN5hyG7pw2AIDC6vZTg9rMM",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2006_09_22_DIG_Andoni_Procesos",
      "year": 2006,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2006_09_22_DIG_Andoni_Procesos.pdf",
      "media": { "driveFileId": "1fyRs1756TUN5hyG7pw2AIDC6vZTg9rMM", "pdf": "1fyRs1756TUN5hyG7pw2AIDC6vZTg9rMM", "thumbnail": "https://drive.google.com/thumbnail?id=1fyRs1756TUN5hyG7pw2AIDC6vZTg9rMM&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2006_DIG_Procedimientos",
      "driveId": "1GGVnAtfZUVUvCiezoyuRdl2YhxgaPOK7",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2006_DIG_Procedimientos",
      "year": 2006,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2006_DIG_Procedimientos.pdf",
      "media": { "driveFileId": "1GGVnAtfZUVUvCiezoyuRdl2YhxgaPOK7", "pdf": "1GGVnAtfZUVUvCiezoyuRdl2YhxgaPOK7", "thumbnail": "https://drive.google.com/thumbnail?id=1GGVnAtfZUVUvCiezoyuRdl2YhxgaPOK7&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2006_DIG_Worlds_of_Flavor_Programa",
      "driveId": "1dSv9jwG_wv80RWUDedyMoh00oRekC5N2",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2006_DIG_Worlds_of_Flavor_Programa",
      "year": 2006,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2006_DIG_Worlds_of_Flavor_Programa.pdf",
      "media": { "driveFileId": "1dSv9jwG_wv80RWUDedyMoh00oRekC5N2", "pdf": "1dSv9jwG_wv80RWUDedyMoh00oRekC5N2", "thumbnail": "https://drive.google.com/thumbnail?id=1dSv9jwG_wv80RWUDedyMoh00oRekC5N2&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2006_Samira_Reposteria_Argelina_Tradi",
      "driveId": "13qwSVDcaukzeHrovVyMiU76RFd-T-hsF",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2006_Samira_Reposteria-Argelina-Tradicional_S-XXI",
      "year": 2006,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2006_Samira_Reposteria-Argelina-Tradicional_S-XXI.pdf",
      "media": { "driveFileId": "13qwSVDcaukzeHrovVyMiU76RFd-T-hsF", "pdf": "13qwSVDcaukzeHrovVyMiU76RFd-T-hsF", "thumbnail": "https://drive.google.com/thumbnail?id=13qwSVDcaukzeHrovVyMiU76RFd-T-hsF&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2007_Digital_INTA_Usos_Industriales_H",
      "driveId": "1b3mSwOtLoSAMPj-hgcD_1QZQ3u5WFKAo",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2007_Digital_INTA_Usos_Industriales_Humanos_Maiz_Sorgo",
      "year": 2007,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2007_Digital_INTA_Usos_Industriales_Humanos_Maiz_Sorgo.pdf",
      "media": { "driveFileId": "1b3mSwOtLoSAMPj-hgcD_1QZQ3u5WFKAo", "pdf": "1b3mSwOtLoSAMPj-hgcD_1QZQ3u5WFKAo", "thumbnail": "https://drive.google.com/thumbnail?id=1b3mSwOtLoSAMPj-hgcD_1QZQ3u5WFKAo&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2007_Recetario_Mugaritz__pdf",
      "driveId": "1RgdjzWIi0GrFDJHz-rgAmgo0j_he-zSd",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2007_Recetario_Mugaritz .pdf",
      "year": 2007,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2007_Recetario_Mugaritz .pdf.pdf",
      "media": { "driveFileId": "1RgdjzWIi0GrFDJHz-rgAmgo0j_he-zSd", "pdf": "1RgdjzWIi0GrFDJHz-rgAmgo0j_he-zSd", "thumbnail": "https://drive.google.com/thumbnail?id=1RgdjzWIi0GrFDJHz-rgAmgo0j_he-zSd&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2008_Alinea_Tecnicas_Mugaritz_Cocina",
      "driveId": "1Sp7aCbMXLGOTzjQswVCS4wN2tVckZEbv",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2008_Alinea_Tecnicas_Mugaritz_Cocina-Vanguardia_S-XXI",
      "year": 2008,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2008_Alinea_Tecnicas_Mugaritz_Cocina-Vanguardia_S-XXI.pdf",
      "media": { "driveFileId": "1Sp7aCbMXLGOTzjQswVCS4wN2tVckZEbv", "pdf": "1Sp7aCbMXLGOTzjQswVCS4wN2tVckZEbv", "thumbnail": "https://drive.google.com/thumbnail?id=1Sp7aCbMXLGOTzjQswVCS4wN2tVckZEbv&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2008_Digital_Paco_Morales_Restaurante",
      "driveId": "1iVCESRG09nnmwyw5C3uXUJ5KyguXKiE-",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2008_Digital_Paco_Morales_Restaurante_Ferrero",
      "year": 2008,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2008_Digital_Paco_Morales_Restaurante_Ferrero.pdf",
      "media": { "driveFileId": "1iVCESRG09nnmwyw5C3uXUJ5KyguXKiE-", "pdf": "1iVCESRG09nnmwyw5C3uXUJ5KyguXKiE-", "thumbnail": "https://drive.google.com/thumbnail?id=1iVCESRG09nnmwyw5C3uXUJ5KyguXKiE-&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2008_Mugaritz_Manual_Agentes_Textura",
      "driveId": "16bu22v3XwSibEjSJFtM18zyZGHLOkkDO",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2008_Mugaritz_Manual-Agentes-Textura_S-XXI",
      "year": 2008,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2008_Mugaritz_Manual-Agentes-Textura_S-XXI.pdf",
      "media": { "driveFileId": "16bu22v3XwSibEjSJFtM18zyZGHLOkkDO", "pdf": "16bu22v3XwSibEjSJFtM18zyZGHLOkkDO", "thumbnail": "https://drive.google.com/thumbnail?id=16bu22v3XwSibEjSJFtM18zyZGHLOkkDO&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2009_DIG_Amilosa_Amilopectina",
      "driveId": "1680vV6wx0276BNQBwpA8V6ySXQe5N46G",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2009_DIG_Amilosa_Amilopectina",
      "year": 2009,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2009_DIG_Amilosa_Amilopectina.pdf",
      "media": { "driveFileId": "1680vV6wx0276BNQBwpA8V6ySXQe5N46G", "pdf": "1680vV6wx0276BNQBwpA8V6ySXQe5N46G", "thumbnail": "https://drive.google.com/thumbnail?id=1680vV6wx0276BNQBwpA8V6ySXQe5N46G&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2009_DIG_Liquenes_Comestibles",
      "driveId": "1P1eZ-zrW2PQ6zGeH8ebtIqzeRbRU-gA8",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2009_DIG_Liquenes_Comestibles",
      "year": 2009,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2009_DIG_Liquenes_Comestibles.pdf",
      "media": { "driveFileId": "1P1eZ-zrW2PQ6zGeH8ebtIqzeRbRU-gA8", "pdf": "1P1eZ-zrW2PQ6zGeH8ebtIqzeRbRU-gA8", "thumbnail": "https://drive.google.com/thumbnail?id=1P1eZ-zrW2PQ6zGeH8ebtIqzeRbRU-gA8&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2010_Anonimo_Historia_Cultivo_Te_S_VI",
      "driveId": "1F2zVqW9xQ8kQze9d06jRP7wvTmm-pjsc",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2010_Anonimo_Historia-Cultivo-Te_S-VIII-XIX",
      "year": 2010,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2010_Anonimo_Historia-Cultivo-Te_S-VIII-XIX.pdf",
      "media": { "driveFileId": "1F2zVqW9xQ8kQze9d06jRP7wvTmm-pjsc", "pdf": "1F2zVqW9xQ8kQze9d06jRP7wvTmm-pjsc", "thumbnail": "https://drive.google.com/thumbnail?id=1F2zVqW9xQ8kQze9d06jRP7wvTmm-pjsc&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2010_Mugaritz_Estudio_Tecnico_Azafran",
      "driveId": "1b93jEbRUU4Ivz9g4FFN2pRfZm7u2VAcs",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2010_Mugaritz_Estudio-Tecnico-Azafran_S-XXI",
      "year": 2010,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2010_Mugaritz_Estudio-Tecnico-Azafran_S-XXI.pdf",
      "media": { "driveFileId": "1b93jEbRUU4Ivz9g4FFN2pRfZm7u2VAcs", "pdf": "1b93jEbRUU4Ivz9g4FFN2pRfZm7u2VAcs", "thumbnail": "https://drive.google.com/thumbnail?id=1b93jEbRUU4Ivz9g4FFN2pRfZm7u2VAcs&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2011_DIG_Contextualizaci_n_Aromas_Sab",
      "driveId": "1TKN9zzFmxnbaa4D-zXE5Gf3VEh68no9d",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2011_DIG_Contextualización_Aromas_Sabores_Cocina_Marroqui",
      "year": 2011,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2011_DIG_Contextualización_Aromas_Sabores_Cocina_Marroqui.pdf",
      "media": { "driveFileId": "1TKN9zzFmxnbaa4D-zXE5Gf3VEh68no9d", "pdf": "1TKN9zzFmxnbaa4D-zXE5Gf3VEh68no9d", "thumbnail": "https://drive.google.com/thumbnail?id=1TKN9zzFmxnbaa4D-zXE5Gf3VEh68no9d&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2011_DIG_Formaci_n_manipulador__de_al",
      "driveId": "1pvPrHms53ycWnLLSy9VemO0N9-dU0qjVf5RpFpW_sj8",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2011_DIG_Formación_manipulador _de_alimentos.gdoc",
      "year": 2011,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2011_DIG_Formación_manipulador _de_alimentos.gdoc",
      "media": { "driveFileId": "1pvPrHms53ycWnLLSy9VemO0N9-dU0qjVf5RpFpW_sj8", "pdf": "1pvPrHms53ycWnLLSy9VemO0N9-dU0qjVf5RpFpW_sj8", "thumbnail": "https://drive.google.com/thumbnail?id=1pvPrHms53ycWnLLSy9VemO0N9-dU0qjVf5RpFpW_sj8&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2011_DIG_Formaci_n_manipulador__de_al",
      "driveId": "1Ssxs-jGLuPdgrgN6yMDAZ-x1xIeZXwOo",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2011_DIG_Formación_manipulador _de_alimentos",
      "year": 2011,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2011_DIG_Formación_manipulador _de_alimentos.pdf",
      "media": { "driveFileId": "1Ssxs-jGLuPdgrgN6yMDAZ-x1xIeZXwOo", "pdf": "1Ssxs-jGLuPdgrgN6yMDAZ-x1xIeZXwOo", "thumbnail": "https://drive.google.com/thumbnail?id=1Ssxs-jGLuPdgrgN6yMDAZ-x1xIeZXwOo&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2011_DIG_La_Neo_tapa",
      "driveId": "1zMtSGQwq0OidXqmvPUxjGc11K0D3KSrN",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2011_DIG_La_Neo_tapa",
      "year": 2011,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2011_DIG_La_Neo_tapa.pdf",
      "media": { "driveFileId": "1zMtSGQwq0OidXqmvPUxjGc11K0D3KSrN", "pdf": "1zMtSGQwq0OidXqmvPUxjGc11K0D3KSrN", "thumbnail": "https://drive.google.com/thumbnail?id=1zMtSGQwq0OidXqmvPUxjGc11K0D3KSrN&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2011_Morales_Taller_Texturas_Paco_Mor",
      "driveId": "110NiGemE1BtpVElpoEDlAwRs9QIm-pOI",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2011_Morales_Taller-Texturas-Paco-Morales_S-XXI",
      "year": 2011,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2011_Morales_Taller-Texturas-Paco-Morales_S-XXI.pdf",
      "media": { "driveFileId": "110NiGemE1BtpVElpoEDlAwRs9QIm-pOI", "pdf": "110NiGemE1BtpVElpoEDlAwRs9QIm-pOI", "thumbnail": "https://drive.google.com/thumbnail?id=110NiGemE1BtpVElpoEDlAwRs9QIm-pOI&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2012_Digital_Moset_Valencia_Open_Pedi",
      "driveId": "1FH9PfhaUL-_2KJQh1x-WNjJwoSCF-fm4",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2012_Digital_Moset_Valencia_Open_Pedidos_Ventas",
      "year": 2012,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2012_Digital_Moset_Valencia_Open_Pedidos_Ventas.pdf",
      "media": { "driveFileId": "1FH9PfhaUL-_2KJQh1x-WNjJwoSCF-fm4", "pdf": "1FH9PfhaUL-_2KJQh1x-WNjJwoSCF-fm4", "thumbnail": "https://drive.google.com/thumbnail?id=1FH9PfhaUL-_2KJQh1x-WNjJwoSCF-fm4&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2012_Digital_Panes_Tradicionales_Magr",
      "driveId": "1oBcZvs3BqcGt5_UO_NL8hQWTkHsmu_N1",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2012_Digital_Panes_Tradicionales_Magreb (1)",
      "year": 2012,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2012_Digital_Panes_Tradicionales_Magreb (1).pdf",
      "media": { "driveFileId": "1oBcZvs3BqcGt5_UO_NL8hQWTkHsmu_N1", "pdf": "1oBcZvs3BqcGt5_UO_NL8hQWTkHsmu_N1", "thumbnail": "https://drive.google.com/thumbnail?id=1oBcZvs3BqcGt5_UO_NL8hQWTkHsmu_N1&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2012_Digital_Panes_Tradicionales_Magr",
      "driveId": "1BUB6y7Z5p2BOouMo_qPyoB6RvIookydS",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2012_Digital_Panes_Tradicionales_Magreb",
      "year": 2012,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2012_Digital_Panes_Tradicionales_Magreb.pdf",
      "media": { "driveFileId": "1BUB6y7Z5p2BOouMo_qPyoB6RvIookydS", "pdf": "1BUB6y7Z5p2BOouMo_qPyoB6RvIookydS", "thumbnail": "https://drive.google.com/thumbnail?id=1BUB6y7Z5p2BOouMo_qPyoB6RvIookydS&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2014_19_07_DIG_Men__Contextualizaci_n",
      "driveId": "1xKgxffrbBwdoQn26snvPsHMpbLhvLcRT",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2014_19_07_DIG_Menú_Contextualización",
      "year": 2014,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2014_19_07_DIG_Menú_Contextualización.pdf",
      "media": { "driveFileId": "1xKgxffrbBwdoQn26snvPsHMpbLhvLcRT", "pdf": "1xKgxffrbBwdoQn26snvPsHMpbLhvLcRT", "thumbnail": "https://drive.google.com/thumbnail?id=1xKgxffrbBwdoQn26snvPsHMpbLhvLcRT&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2015_10_DIG_Recetario_Varios",
      "driveId": "1EyK6iNOR1z85KuKvO8bKBzedDnqVUL52",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2015_10_DIG_Recetario_Varios",
      "year": 2015,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2015_10_DIG_Recetario_Varios.pdf",
      "media": { "driveFileId": "1EyK6iNOR1z85KuKvO8bKBzedDnqVUL52", "pdf": "1EyK6iNOR1z85KuKvO8bKBzedDnqVUL52", "thumbnail": "https://drive.google.com/thumbnail?id=1EyK6iNOR1z85KuKvO8bKBzedDnqVUL52&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2015_DIG_ActaReunion_PacoMorales_Ferr",
      "driveId": "1Xe_IUcyzHtfHJUHDwFxkHLZbrPL7mOg4",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2015_DIG_ActaReunion_PacoMorales_FerranAdria_ProyectoNoor_Bullilab",
      "year": 2015,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2015_DIG_ActaReunion_PacoMorales_FerranAdria_ProyectoNoor_Bullilab.pdf",
      "media": { "driveFileId": "1Xe_IUcyzHtfHJUHDwFxkHLZbrPL7mOg4", "pdf": "1Xe_IUcyzHtfHJUHDwFxkHLZbrPL7mOg4", "thumbnail": "https://drive.google.com/thumbnail?id=1Xe_IUcyzHtfHJUHDwFxkHLZbrPL7mOg4&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2015_Tecnico_Manual_Salsas_Hosteleria",
      "driveId": "1fZ4cWynvZL5GfdjYCFdzXAOHYZlultjH",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2015_Tecnico_Manual-Salsas-Hosteleria_.pdf",
      "year": 2015,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2015_Tecnico_Manual-Salsas-Hosteleria_.pdf.pdf",
      "media": { "driveFileId": "1fZ4cWynvZL5GfdjYCFdzXAOHYZlultjH", "pdf": "1fZ4cWynvZL5GfdjYCFdzXAOHYZlultjH", "thumbnail": "https://drive.google.com/thumbnail?id=1fZ4cWynvZL5GfdjYCFdzXAOHYZlultjH&sz=w1000" }
    },
    {
      "id": "local-ctx-06_2015_Tecnico_Mugaritz_Manual_Consomes",
      "driveId": "1MCSEuF-oV9RNP_XJEWnnASpo1KXXT0YB",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_2015_Tecnico_Mugaritz_Manual-Consomes-Potajes-Cremas_S-XXI",
      "year": 2015,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_2015_Tecnico_Mugaritz_Manual-Consomes-Potajes-Cremas_S-XXI.pdf",
      "media": { "driveFileId": "1MCSEuF-oV9RNP_XJEWnnASpo1KXXT0YB", "pdf": "1MCSEuF-oV9RNP_XJEWnnASpo1KXXT0YB", "thumbnail": "https://drive.google.com/thumbnail?id=1MCSEuF-oV9RNP_XJEWnnASpo1KXXT0YB&sz=w1000" }
    },
    {
      "id": "local-ctx-06_Copia_de_01_2005_10_DIG_Dosier_de_pre",
      "driveId": "1p-6GXL77NAbFfL3sOb2YE7recJQutBcK",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_Copia de 01_2005_10_DIG_Dosier_de_prensa",
      "year": 2005,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_Copia de 01_2005_10_DIG_Dosier_de_prensa.pdf",
      "media": { "driveFileId": "1p-6GXL77NAbFfL3sOb2YE7recJQutBcK", "pdf": "1p-6GXL77NAbFfL3sOb2YE7recJQutBcK", "thumbnail": "https://drive.google.com/thumbnail?id=1p-6GXL77NAbFfL3sOb2YE7recJQutBcK&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_2003_La_Cuisine_Libanese_Rescate",
      "driveId": "18MbTqW3FNUGnnCZtXY1alB0KyBfnVTvL",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_2003_La_Cuisine_Libanese_Rescate.pdf3",
      "year": 2003,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_2003_La_Cuisine_Libanese_Rescate.pdf3",
      "media": { "driveFileId": "18MbTqW3FNUGnnCZtXY1alB0KyBfnVTvL", "pdf": "18MbTqW3FNUGnnCZtXY1alB0KyBfnVTvL", "thumbnail": "https://drive.google.com/thumbnail?id=18MbTqW3FNUGnnCZtXY1alB0KyBfnVTvL&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Abderraman_lll_Cabrito_Pastor",
      "driveId": "1ltFCmTHWH9KSN3hezLSYiVyQl1cka5xJ",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Abderraman_lll_Cabrito_Pastor",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Abderraman_lll_Cabrito_Pastor.pdf",
      "media": { "driveFileId": "1ltFCmTHWH9KSN3hezLSYiVyQl1cka5xJ", "pdf": "1ltFCmTHWH9KSN3hezLSYiVyQl1cka5xJ", "thumbnail": "https://drive.google.com/thumbnail?id=1ltFCmTHWH9KSN3hezLSYiVyQl1cka5xJ&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Albar_n_Gumendi_Producto",
      "driveId": "1Fd-zsFuGLuGJ9mCFhWj9XtPZjgHIsiR1",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Albarán_Gumendi_Producto",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Albarán_Gumendi_Producto.Pdf",
      "media": { "driveFileId": "1Fd-zsFuGLuGJ9mCFhWj9XtPZjgHIsiR1", "pdf": "1Fd-zsFuGLuGJ9mCFhWj9XtPZjgHIsiR1", "thumbnail": "https://drive.google.com/thumbnail?id=1Fd-zsFuGLuGJ9mCFhWj9XtPZjgHIsiR1&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_CONTEXTUALIZACI_N_AGRICULTURA_AL",
      "driveId": "1bmJQ4mjJmpDGMB9BcskThvifysMZ3SX4",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_CONTEXTUALIZACIÓN_AGRICULTURA_AL_ANDALUS",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_CONTEXTUALIZACIÓN_AGRICULTURA_AL_ANDALUS.pdf",
      "media": { "driveFileId": "1bmJQ4mjJmpDGMB9BcskThvifysMZ3SX4", "pdf": "1bmJQ4mjJmpDGMB9BcskThvifysMZ3SX4", "thumbnail": "https://drive.google.com/thumbnail?id=1bmJQ4mjJmpDGMB9BcskThvifysMZ3SX4&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Cocina_contextualizaci_n_Kosher_m",
      "driveId": "1FStAAp1gQJCR5lufzGj2FxUQuaGDhl4X",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Cocina_contextualización_Kosher_magrebí.pdf.",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Cocina_contextualización_Kosher_magrebí.pdf..pdf",
      "media": { "driveFileId": "1FStAAp1gQJCR5lufzGj2FxUQuaGDhl4X", "pdf": "1FStAAp1gQJCR5lufzGj2FxUQuaGDhl4X", "thumbnail": "https://drive.google.com/thumbnail?id=1FStAAp1gQJCR5lufzGj2FxUQuaGDhl4X&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Colaboraci_n_Grupos_investigaci_n",
      "driveId": "1GWcIZA6-tDS2i25g4sYMXKWRkzTtYIzN",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Colaboración_Grupos_investigación",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Colaboración_Grupos_investigación.pdf",
      "media": { "driveFileId": "1GWcIZA6-tDS2i25g4sYMXKWRkzTtYIzN", "pdf": "1GWcIZA6-tDS2i25g4sYMXKWRkzTtYIzN", "thumbnail": "https://drive.google.com/thumbnail?id=1GWcIZA6-tDS2i25g4sYMXKWRkzTtYIzN&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Contextualizaci_n_Al_Andalus",
      "driveId": "1bR5kjsOKuX-TKCUf9bOP7rTZli026YXQ",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Contextualización_Al_Andalus",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Contextualización_Al_Andalus.pdf",
      "media": { "driveFileId": "1bR5kjsOKuX-TKCUf9bOP7rTZli026YXQ", "pdf": "1bR5kjsOKuX-TKCUf9bOP7rTZli026YXQ", "thumbnail": "https://drive.google.com/thumbnail?id=1bR5kjsOKuX-TKCUf9bOP7rTZli026YXQ&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Contextualizaci_n_Herencia__rabep",
      "driveId": "1jG0KIWoq9NPiXI5SX8yhjavAf5aJU8LK",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Contextualización_Herencia_Árabepdf",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Contextualización_Herencia_Árabepdf.pdf",
      "media": { "driveFileId": "1jG0KIWoq9NPiXI5SX8yhjavAf5aJU8LK", "pdf": "1jG0KIWoq9NPiXI5SX8yhjavAf5aJU8LK", "thumbnail": "https://drive.google.com/thumbnail?id=1jG0KIWoq9NPiXI5SX8yhjavAf5aJU8LK&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Contextualizaci_n_Servicio_porla",
      "driveId": "1xr1c5Ibf2DxV3lA90KYiaZI-u6Dn7fFk",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Contextualización_Servicio_porla_historia",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Contextualización_Servicio_porla_historia.pdf",
      "media": { "driveFileId": "1xr1c5Ibf2DxV3lA90KYiaZI-u6Dn7fFk", "pdf": "1xr1c5Ibf2DxV3lA90KYiaZI-u6Dn7fFk", "thumbnail": "https://drive.google.com/thumbnail?id=1xr1c5Ibf2DxV3lA90KYiaZI-u6Dn7fFk&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_ESCANDALLO_COSTES_PLATOS_MUGARITZ",
      "driveId": "1-V5tUa6jiBRFemM9wpF0GO-7Hzq5ohNm",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_ESCANDALLO_COSTES_PLATOS_MUGARITZ",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_ESCANDALLO_COSTES_PLATOS_MUGARITZ.pdf",
      "media": { "driveFileId": "1-V5tUa6jiBRFemM9wpF0GO-7Hzq5ohNm", "pdf": "1-V5tUa6jiBRFemM9wpF0GO-7Hzq5ohNm", "thumbnail": "https://drive.google.com/thumbnail?id=1-V5tUa6jiBRFemM9wpF0GO-7Hzq5ohNm&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_EVENTO_MENU_BODA_MAITE_ION",
      "driveId": "1sdNgyVnvi70iMqDOCAIPs_y70vyGY7rw",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_EVENTO_MENU_BODA_MAITE_ION",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_EVENTO_MENU_BODA_MAITE_ION.pdf",
      "media": { "driveFileId": "1sdNgyVnvi70iMqDOCAIPs_y70vyGY7rw", "pdf": "1sdNgyVnvi70iMqDOCAIPs_y70vyGY7rw", "thumbnail": "https://drive.google.com/thumbnail?id=1sdNgyVnvi70iMqDOCAIPs_y70vyGY7rw&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_El_Agua_Los_T__s",
      "driveId": "1_Ey9vFLW9Z4QiRltcwtE9wUosOnhigs1",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_El_Agua_Los_Té_s",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_El_Agua_Los_Té_s.pdf",
      "media": { "driveFileId": "1_Ey9vFLW9Z4QiRltcwtE9wUosOnhigs1", "pdf": "1_Ey9vFLW9Z4QiRltcwtE9wUosOnhigs1", "thumbnail": "https://drive.google.com/thumbnail?id=1_Ey9vFLW9Z4QiRltcwtE9wUosOnhigs1&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_INULINA_CONTEXTUALIZACION",
      "driveId": "1nP5ph6SpEycx6M7OOiU26fPOyhOfhww9",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_INULINA_CONTEXTUALIZACION",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_INULINA_CONTEXTUALIZACION.pdf",
      "media": { "driveFileId": "1nP5ph6SpEycx6M7OOiU26fPOyhOfhww9", "pdf": "1nP5ph6SpEycx6M7OOiU26fPOyhOfhww9", "thumbnail": "https://drive.google.com/thumbnail?id=1nP5ph6SpEycx6M7OOiU26fPOyhOfhww9&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_INVESTIGACION_EXTRACCION_AZAFRAN",
      "driveId": "15CdsvlGpkMyiSsUEXXIQvtTaqt4m9572",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_INVESTIGACION_EXTRACCION_AZAFRAN",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_INVESTIGACION_EXTRACCION_AZAFRAN.pdf",
      "media": { "driveFileId": "15CdsvlGpkMyiSsUEXXIQvtTaqt4m9572", "pdf": "15CdsvlGpkMyiSsUEXXIQvtTaqt4m9572", "thumbnail": "https://drive.google.com/thumbnail?id=15CdsvlGpkMyiSsUEXXIQvtTaqt4m9572&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_LISTADO_BOTANICO_VEGETALES_FLORES",
      "driveId": "1Dp24VeM5sdFInBqLa48l-pB3gmSFlomh",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_LISTADO_BOTANICO_VEGETALES_FLORES",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_LISTADO_BOTANICO_VEGETALES_FLORES.pdf",
      "media": { "driveFileId": "1Dp24VeM5sdFInBqLa48l-pB3gmSFlomh", "pdf": "1Dp24VeM5sdFInBqLa48l-pB3gmSFlomh", "thumbnail": "https://drive.google.com/thumbnail?id=1Dp24VeM5sdFInBqLa48l-pB3gmSFlomh&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_La_Rega___Contextualizaci_n",
      "driveId": "1gi1qJGhZyJm8lMPThB8LQKKlBdb_XDWk",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_La_Regañá_Contextualización",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_La_Regañá_Contextualización.pdf",
      "media": { "driveFileId": "1gi1qJGhZyJm8lMPThB8LQKKlBdb_XDWk", "pdf": "1gi1qJGhZyJm8lMPThB8LQKKlBdb_XDWk", "thumbnail": "https://drive.google.com/thumbnail?id=1gi1qJGhZyJm8lMPThB8LQKKlBdb_XDWk&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Listado_de_Restaurantes",
      "driveId": "15vzFEwjTMo5EHbkXtFSWnq3EO8Gl1Ayr",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Listado_de_Restaurantes",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Listado_de_Restaurantes.Pdf",
      "media": { "driveFileId": "15vzFEwjTMo5EHbkXtFSWnq3EO8Gl1Ayr", "pdf": "15vzFEwjTMo5EHbkXtFSWnq3EO8Gl1Ayr", "thumbnail": "https://drive.google.com/thumbnail?id=15vzFEwjTMo5EHbkXtFSWnq3EO8Gl1Ayr&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Noor_Vajilla",
      "driveId": "1caEK11Wrgbd2x4rDolZfqBKtOc31Vhpp",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Noor_Vajilla",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Noor_Vajilla.pdf",
      "media": { "driveFileId": "1caEK11Wrgbd2x4rDolZfqBKtOc31Vhpp", "pdf": "1caEK11Wrgbd2x4rDolZfqBKtOc31Vhpp", "thumbnail": "https://drive.google.com/thumbnail?id=1caEK11Wrgbd2x4rDolZfqBKtOc31Vhpp&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_PERFIL_PACO_MORALES_NORDIC_CHALLE",
      "driveId": "19ULBCa4tkf-_hs3-fMep2fMXAyrhZ9Tl",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_PERFIL_PACO_MORALES_NORDIC_CHALLENGE",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_PERFIL_PACO_MORALES_NORDIC_CHALLENGE.pdf",
      "media": { "driveFileId": "19ULBCa4tkf-_hs3-fMep2fMXAyrhZ9Tl", "pdf": "19ULBCa4tkf-_hs3-fMep2fMXAyrhZ9Tl", "thumbnail": "https://drive.google.com/thumbnail?id=19ULBCa4tkf-_hs3-fMep2fMXAyrhZ9Tl&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Primeros_Ingredientes_Al_Andalus",
      "driveId": "1fWJR279w7sJnk4806ji5-ayjN4ItkpeL",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Primeros_Ingredientes_Al_Andalus",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Primeros_Ingredientes_Al_Andalus.pdf",
      "media": { "driveFileId": "1fWJR279w7sJnk4806ji5-ayjN4ItkpeL", "pdf": "1fWJR279w7sJnk4806ji5-ayjN4ItkpeL", "thumbnail": "https://drive.google.com/thumbnail?id=1fWJR279w7sJnk4806ji5-ayjN4ItkpeL&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_RECETARIO_DULCE_VANIDAD_Y_PUDING",
      "driveId": "1ywnI-E0X559vo50jwrlLl_Zl9NHSp9Ld",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_RECETARIO_DULCE_VANIDAD_Y_PUDING",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_RECETARIO_DULCE_VANIDAD_Y_PUDING.pdf",
      "media": { "driveFileId": "1ywnI-E0X559vo50jwrlLl_Zl9NHSp9Ld", "pdf": "1ywnI-E0X559vo50jwrlLl_Zl9NHSp9Ld", "thumbnail": "https://drive.google.com/thumbnail?id=1ywnI-E0X559vo50jwrlLl_Zl9NHSp9Ld&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Recetas_Varias",
      "driveId": "1cgaMxmbeNrSTnjVSvgVzx6pnVVlOh_SM",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Recetas_Varias",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Recetas_Varias.pdf",
      "media": { "driveFileId": "1cgaMxmbeNrSTnjVSvgVzx6pnVVlOh_SM", "pdf": "1cgaMxmbeNrSTnjVSvgVzx6pnVVlOh_SM", "thumbnail": "https://drive.google.com/thumbnail?id=1cgaMxmbeNrSTnjVSvgVzx6pnVVlOh_SM&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Siglo_Xl_Almor_vides_Contextualiz",
      "driveId": "1T8wCq38gqIeY-OxAsAfHQuHS-aMTmxp-",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Siglo_Xl_Almorávides_Contextualización",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Siglo_Xl_Almorávides_Contextualización.pdf",
      "media": { "driveFileId": "1T8wCq38gqIeY-OxAsAfHQuHS-aMTmxp-", "pdf": "1T8wCq38gqIeY-OxAsAfHQuHS-aMTmxp-", "thumbnail": "https://drive.google.com/thumbnail?id=1T8wCq38gqIeY-OxAsAfHQuHS-aMTmxp-&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Siglo_Xl_Almor_vides_Contextualiz",
      "driveId": "11ZWUtbTvRW4xi_DGRCr7uhSEG6lte1IPGudFGxGsZ7s",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Siglo_Xl_Almorávides_Contextualización.pdf.gdoc",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Siglo_Xl_Almorávides_Contextualización.pdf.gdoc",
      "media": { "driveFileId": "11ZWUtbTvRW4xi_DGRCr7uhSEG6lte1IPGudFGxGsZ7s", "pdf": "11ZWUtbTvRW4xi_DGRCr7uhSEG6lte1IPGudFGxGsZ7s", "thumbnail": "https://drive.google.com/thumbnail?id=11ZWUtbTvRW4xi_DGRCr7uhSEG6lte1IPGudFGxGsZ7s&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_Siglo_Xl_Men__Wusul",
      "driveId": "1cpCAo6qQOZFbmT8Fr-WdDmHXkinXW_aH",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_Siglo_Xl_Menú_Wusul",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_Siglo_Xl_Menú_Wusul.pdf",
      "media": { "driveFileId": "1cpCAo6qQOZFbmT8Fr-WdDmHXkinXW_aH", "pdf": "1cpCAo6qQOZFbmT8Fr-WdDmHXkinXW_aH", "thumbnail": "https://drive.google.com/thumbnail?id=1cpCAo6qQOZFbmT8Fr-WdDmHXkinXW_aH&sz=w1000" }
    },
    {
      "id": "local-ctx-06_DIG_contextualizaci_n_Espelta_pdf",
      "driveId": "1c9oz7GvqTcILXlw8XtosCpTNkXF-zxsT",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_DIG_contextualización_Espelta.pdf.",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_DIG_contextualización_Espelta.pdf..pdf",
      "media": { "driveFileId": "1c9oz7GvqTcILXlw8XtosCpTNkXF-zxsT", "pdf": "1c9oz7GvqTcILXlw8XtosCpTNkXF-zxsT", "thumbnail": "https://drive.google.com/thumbnail?id=1c9oz7GvqTcILXlw8XtosCpTNkXF-zxsT&sz=w1000" }
    },
    {
      "id": "local-ctx-06_FICHA_TECNICA_GLUCIDOS_MUCILAGOS",
      "driveId": "1f2wfZwDdR1Mj9Lj34nloBY_WG1AmCD3x",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "06_FICHA_TECNICA_GLUCIDOS_MUCILAGOS",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/06_FICHA_TECNICA_GLUCIDOS_MUCILAGOS.pdf",
      "media": { "driveFileId": "1f2wfZwDdR1Mj9Lj34nloBY_WG1AmCD3x", "pdf": "1f2wfZwDdR1Mj9Lj34nloBY_WG1AmCD3x", "thumbnail": "https://drive.google.com/thumbnail?id=1f2wfZwDdR1Mj9Lj34nloBY_WG1AmCD3x&sz=w1000" }
    },
    {
      "id": "local-ctx-Adobe_Scan_07_mar_2026__6",
      "driveId": "1ISnrnVNuIsdC4EU1vqSnnpJGTqwyW6FC",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "Adobe Scan 07 mar 2026 (6)",
      "year": 2026,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/Adobe Scan 07 mar 2026 (6).pdf",
      "media": { "driveFileId": "1ISnrnVNuIsdC4EU1vqSnnpJGTqwyW6FC", "pdf": "1ISnrnVNuIsdC4EU1vqSnnpJGTqwyW6FC", "thumbnail": "https://drive.google.com/thumbnail?id=1ISnrnVNuIsdC4EU1vqSnnpJGTqwyW6FC&sz=w1000" }
    },
    {
      "id": "local-ctx-Adobe_Scan_10_mar_2026__2",
      "driveId": "1V63ECTaCxXYVYgDCLQaaZKkff-syUSQ1",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "Adobe Scan 10 mar 2026 (2)",
      "year": 2026,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/Adobe Scan 10 mar 2026 (2).pdf",
      "media": { "driveFileId": "1V63ECTaCxXYVYgDCLQaaZKkff-syUSQ1", "pdf": "1V63ECTaCxXYVYgDCLQaaZKkff-syUSQ1", "thumbnail": "https://drive.google.com/thumbnail?id=1V63ECTaCxXYVYgDCLQaaZKkff-syUSQ1&sz=w1000" }
    },
    {
      "id": "local-ctx-TRANSCRIPT_06_DIG_Siglo_Xl_Almor_vides_C",
      "driveId": "1pAgEZUBF_xxW84cyOKeYw1xj2Zm2pnZb",
      "category": "06_PRODUCTO_CONTEXTUALIZACION",
      "title": "TRANSCRIPT_06_DIG_Siglo_Xl_Almorávides_Contextualización",
      "year": 2000,
      "type": "book",
      "eraId": "S21",
      "language": "es",
      "source": "Archivo Digital Noor",
      "tags": ["Contextualización", "Producto", "06_PRODUCTO_CONTEXTUALIZACION"],
      "regions": ["QURTUBA"],
      "coordinates": [37.8847, -4.7791],
      "localPath": "G:/Mi unidad/Noor_ 2026_archivos/ARCHIVO_DIGITAL_NOOR/06_PRODUCTO_CONTEXTUALIZACION/TRANSCRIPT_06_DIG_Siglo_Xl_Almorávides_Contextualización.docx",
      "media": { "driveFileId": "1pAgEZUBF_xxW84cyOKeYw1xj2Zm2pnZb", "pdf": "1pAgEZUBF_xxW84cyOKeYw1xj2Zm2pnZb", "thumbnail": "https://drive.google.com/thumbnail?id=1pAgEZUBF_xxW84cyOKeYw1xj2Zm2pnZb&sz=w1000" }
    }